import type { Metadata } from "next";
import { WeatherProvider } from "@/context/WeatherContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "assets/favicon-32x32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning data-qb-installed="true">
      <body>
        <WeatherProvider>{children}</WeatherProvider>
      </body>
    </html>
  );
}
